### PR TITLE
Need to remove priority logic

### PR DESCRIPTION
**Pull request by terrazoon**
## Description

Notify UK had two providers and would dynamically shift which provider to use based on whether a message had 'priority'.   However we only have one provider, so the whole concept of priority doesn't mean anything for us.  Remove the remaining priority logic.

## Security Considerations

N/A

### CODE REVIEW

**Review by xlorepdarkhelm — CHANGES_REQUESTED** [review]
What about the priority columns in the models.py file (`ProviderDetails` and `ProviderDetailsHistory` classes)? This would then need a migration as well, but if this is not needed, I think it would be best to be removed from the DB.

**Review by xlorepdarkhelm — CHANGES_REQUESTED** [review]
Still seeing no changes to the `models.py` file, despite there now being a migration.

**Comment by terrazoon** [comment]
> Still seeing no changes to the `models.py` file, despite there now being a migration.

The priority column has been removed in models.py.  Maybe you need to refresh or something?  The GitHub view gets out of date sometimes, but you can look at the code on the branch and see they're removed.

**Review by A-Shumway42 — APPROVED** [review]
LGTM!

**Review by xlorepdarkhelm — APPROVED** [review]
LGTM

**Pull request merged**
