### PR TITLE
make user command

### PR DESCRIPTION
**Pull request by terrazoon**
## Description

To improve logging of the sign-in flow without revealing PII, we need to obtain the user_id from production.  So, write a command that takes a user's email address and dumps user info to the platform admin's terminal.

## Security Considerations

We are dumping info that contains PII to the the platform admin's terminal.

### CODE REVIEW

**Review by xlorepdarkhelm — APPROVED** [review]
LGTM

**Comment by ccostino** [comment]
Hopefully another merge with `main` fixes the test coverage amount again!

**Review by xlorepdarkhelm — APPROVED** [review]
LGTM

**Review by ccostino — APPROVED** [review]
Thanks, @terrazoon!

**Pull request merged**
