### PR TITLE
remove dead code

### PR DESCRIPTION
**Pull request by terrazoon**
## Description

The Vulture tool scans for dead code.  In our build process, it runs automatically, but we have tuned the confidence level to 100 percent.  So if guaranteed dead code exists, the build will fail.   

However, it is possible to tune Vulture down to 60 percent confidence, at which point it makes informed guesses about whether code is dead or not.   With these findings, a developer has to go through and verify "yes, this code looks dead" but still it is a handy way to find questionable code.

In this PR we remove a few things that are flagged by Vulture and clearly are dead.

## Security Considerations

N/A

### CODE REVIEW

**Review by xlorepdarkhelm — COMMENTED** [review]
LGTM, just wondering though, should the code be commented out or removed? We'll have the code existing in git, so wondering if we need to really keep it in the code, as commented out code tends to make things messy.

**Review by ccostino — CHANGES_REQUESTED** [review]
Thanks for going through and gathering up a few things here, @terrazoon!

I agree with @xlorepdarkhelm, let's just straight up remove it.  If it's still necessary, it'll be obvious we need to keep it and we can put it back in, but let's not leave it to chance that this all continues to linger.

**Comment by ccostino** [comment]
We also need an updated PR description with the details of the PR instead of the template, please. 🙂

**Review by ccostino — APPROVED** [review]
Thanks, @terrazoon!

**Pull request merged**
