### PR TITLE
Import notify-sandbox space

### PR DESCRIPTION
**Pull request by jskinne3**
## Description

Brings a "space," a thing which exists out on Cloud.gov, under Terraform management 

* Restore the `notify-sandbox` Cloud Foundry space resource that was removed in #891 
* Add `import` block that hooks up to the existing space

This is a preliminary, experimental restoration of a bunch of Terraform configuration changes. More PRs to come if this works out.

## To do

Because I wanted to create the smallest possible delta that would prove the concept of importing a space, there are things this PR *dosen't* do, but a later one will:
* remove the deprecated `recursive_delete` argument 
* use the `prevent_destroy` argument
* use local variables at all

## Deployment

The `import` bock used in this PR is supported only by Terraform v1.5 and above. It relies on PR #923 which ensures the Terraform version number is at least this high.

🛠️  Only deploy this PR *after* number 923 has been deployed and verified

### CODE REVIEW

**Review by xlorepdarkhelm — APPROVED** [review]
LGTM

**Review by ccostino — COMMENTED** [review]
Thanks, @jskinne3!  The approach looks right to me and the changes fine, though as you'll note we'll have to rebase with `main` once the other stuff is merged first to make sure that it doesn't _undo_ or _revert_ anything.

**Comment by ccostino** [comment]
@jskinne3, do we need to come back to this PR?  And are the things it previously required now in place, or are there other changes that still need to be accounted for first?

**Comment by jskinne3** [comment]
Because of the difficulty we encountered importing the Sandbox space and then running terraform destroy I think the practice of importing our existing spaces is a bad idea, at least for now. Hence I am closing this PR, as well as #931 .

To answer your question @ccostino , the original purpose we were trying to accomplish here is now being addressed in #1072 and #1073

**Pull request closed without merging**
